DROP TABLE IF EXISTS `finish_job`;
CREATE TABLE `finish_job` (
  `internal_id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_internal_id` int(11),
  `options` int(11) DEFAULT NULL,
  `num_processors` int(11) DEFAULT NULL,
  `j_status` int(11) DEFAULT NULL,
  `submit_time` datetime default '0000-00-00 00:00:00',
  `start_time` datetime default '0000-00-00 00:00:00',
  `end_time` datetime default '0000-00-00 00:00:00',
  `submit_year` int(11) DEFAULT NULL,
  `submit_month` int(11) DEFAULT NULL,
  `submit_mday` int(11) DEFAULT NULL,
  `submit_wday` int(11) DEFAULT NULL,
  `submit_hour` int(11) DEFAULT NULL,
  `submit_min` int(11) DEFAULT NULL,
  `submit_sec` int(11) DEFAULT NULL,
  `queue` tinytext,
  `ru_utime` double default null,
  `ru_stime` double default null,
  `ru_maxrss` double default null,
  `ru_ixrss` double default null,  
  `ru_idrss` double default null,
  `ru_isrss` double default null,
  `ru_minflt` double default null,
  `ru_majflt` double default null,
  `ru_nswap` double default null,
  `ru_inblock` double default null,
  `ru_oublock` double default null,
  `ru_msgsnd` double default null,
  `ru_msgrcv` double default null,
  `ru_nsignals` double default null,
  `ru_nvcsw` double default null,
  `ru_nivcsw` double default null,
  `resource_req` tinytext,
  `from_host` tinytext,
  `cwd` tinytext,
  `in_file` tinytext,
  `out_file` tinytext,
  `err_file` tinytext,
  `in_file_spool` tinytext,
  `command_Spool` tinytext,
  `job_file` tinytext,
  `num_asked_hosts` int(11) DEFAULT NULL,
  `asked_hosts` text,
  `host_factor` double DEFAULT NULL,
  `num_ex_hosts` int(11) DEFAULT NULL,
  `exec_hosts` text,
  `cpu_time` double DEFAULT NULL,
  `job_name` tinytext,
  `depend_cond` tinytext,
  `time_event` tinytext,
  `pre_exec_cmd` tinytext,
  `mail_user` tinytext,
  `project_name` tinytext,
  `exit_status` int(11) DEFAULT NULL,
  `max_num_processors` int(11) DEFAULT NULL,
  `login_shell` tinytext,
  `idx` int(11) DEFAULT NULL,
  `max_rmem` int(11) DEFAULT NULL,
  `max_rswap` int(11) DEFAULT NULL,
  `rsv_id` tinytext,
  `sla` tinytext,
  `except_mask` int(11) DEFAULT NULL,
  `additional_Info` tinytext,
  `exit_info` int(11) DEFAULT NULL,
  `warning_time_period` int(11) DEFAULT NULL,
  `warning_action` tinytext,
  `charged_SAAP` tinytext,
  `license_project` tinytext,
  `app` tinytext,
  `post_exec_cmd` tinytext,
  `runtime_estimation` int(11) DEFAULT NULL,
  `jgroup` tinytext,
  `options2` int(11) DEFAULT NULL,
  `requeue_e_values` tinytext,
  `notify_cmd` tinytext,
  `last_resize_time` datetime default '0000-00-00 00:00:00',
  `job_description` tinytext,
  `command` text,
  PRIMARY KEY (`internal_id`,`submit_time`),
  KEY `job_id` (`job_id`),
  KEY `user_id` (`user_id`),
  KEY `user_internal_id` (`user_internal_id`),
  KEY `submit_time` (`submit_time`),
  KEY `start_time` (`start_time`),
  KEY `end_time` (`end_time`),
  KEY `queue` (`queue`(255)),
  KEY `cwd` (`cwd`(255))
) ENGINE=MyISAM AUTO_INCREMENT=2602698 DEFAULT CHARSET=latin1
